name: counter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.3.9
  riverpod_annotation: ^2.1.3

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
dev_dependencies:

  riverpod_generator: ^2.3.0
  freezed: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
