name: counter_workshop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  go_router: ^4.4.1
  logging: ^1.0.2
  logging_appenders: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files
  
  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf

  assets:
    - assets/images/ # .png/.jpg images
    - assets/icons/ # .svg icons
    - assets/fonts/ # Custom Fonts
    - assets/launcher_icon/ # App icon image to generate from
