// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-I5vALrCY96_Ik6k6xXYAMNYH0ataZk',
    appId: '1:494146543454:web:6b2c244550729b2eb839cf',
    messagingSenderId: '494146543454',
    projectId: 'coodoo-counter',
    authDomain: 'coodoo-counter.firebaseapp.com',
    storageBucket: 'coodoo-counter.appspot.com',
    measurementId: 'G-36TPCL5TQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkXODn5jr6ZPVT-nvEnhR8SA0muJXKi10',
    appId: '1:494146543454:android:395c0001abb99538b839cf',
    messagingSenderId: '494146543454',
    projectId: 'coodoo-counter',
    storageBucket: 'coodoo-counter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMs7TVHaSZfJ4wuiWl9J51RIDZp3B_6-Y',
    appId: '1:494146543454:ios:95afba22ce30e446b839cf',
    messagingSenderId: '494146543454',
    projectId: 'coodoo-counter',
    storageBucket: 'coodoo-counter.appspot.com',
    iosClientId: '494146543454-hp7db16o4bqgqa9b93nq35nch0230tks.apps.googleusercontent.com',
    iosBundleId: 'de.coodoo.clicker.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMs7TVHaSZfJ4wuiWl9J51RIDZp3B_6-Y',
    appId: '1:494146543454:ios:1e134bf772f08b68b839cf',
    messagingSenderId: '494146543454',
    projectId: 'coodoo-counter',
    storageBucket: 'coodoo-counter.appspot.com',
    iosClientId: '494146543454-q4mh4a8n5a3ii2h2f5o9osj3fteh9f7o.apps.googleusercontent.com',
    iosBundleId: 'de.coodoo.counterWorkshop',
  );
}
