name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: 'stable'
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
  # Check app for format and lint exceptions (fail fast)
  # check:
  #   needs: build
  #   runs-on: macos-latest
  #   steps:
      # before
      - run: flutter --version
      # just run
      - run: make format
      - run: make clean
      - run: make lint
  # # Check code quality
  # code_quality:
  #   needs: build
  #   runs-on: macos-latest
  #   steps:
  #     # before
      - run: export PATH="$PATH":"$HOME/.pub-cache/bin"
      - run: flutter pub global activate dart_code_metrics
      # just run
      - run: metrics lib -r codeclimate  > gh-code-quality-report.json
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          path: gh-code-quality-report.json
  # Run tests and report quality
  # test:
  #   needs: build
  #   runs-on: macos-latest
  #   steps:
      # before
      - run: export PATH="$PATH":"$HOME/.pub-cache/bin"
      - run: flutter pub global activate junitreport
      # just run
      - run: flutter test --machine --coverage | tojunit -o report.xml
      - run: lcov --summary coverage/lcov.info
      - run: genhtml coverage/lcov.info --output=coverage

    # Build the app to check if release builds still work
  # apk:
  #   needs: [build, check]
  #   runs-on: macos-latest
  #   steps:
      - run: make build-android-apk
      - name: 'Upload APK'
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build-output/app.apk
          retention-days: 2
      